### ISSUE TITLE
[code-review] Главная страница бесполезна

### ISSUE THREAD

**Issue by sheerockoff** [sarkisyan-m/TgBotInt#19]
Шаблоны, шаблонизатор, интернационализация, npm, yarn, ассеты, web-pack, bootstrap и другие зависимости необходимы для того, чтобы вывести на главной странице "Добро пожаловать! Тут должен быть контент!".

От главной страницы можно отказаться, и отказаться от зависимостей (npm, yarn, webpack, symfony/webpack-encore и т.д.), и мёртвого кода (контроллер, шаблоны, ассеты и т.п.).

https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Controller/DefaultController.php#L11-L19

https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/templates/index.html.twig#L29-L33

https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/translations/index.ru.yaml#L7-L9

https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/package.json#L2-L9

https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/package.json#L18-L23

**Comment by sarkisyan-m** [comment]
в проде удалю. вопрос пока оставим, чтобы не забыть
