### ISSUE TITLE
[code-review] Глубокая вложенность блоков if

### ISSUE THREAD

**Issue by sheerockoff** [sarkisyan-m/TgBotInt#21]
https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Controller/TelegramController.php#L106-L166

Большие блоки `if` с глубокой вложенностью. Такой код тяжело читать. Желательно избегать подобного. 

https://github.com/jupeter/clean-code-php#avoid-nesting-too-deeply-and-return-early-part-1
https://github.com/jupeter/clean-code-php#avoid-nesting-too-deeply-and-return-early-part-2

Например:
```php
if (!$this->isTg) {
    return new Response('', Response::HTTP_FORBIDDEN);
}

if (!$this->tgRequest->getRequestType()) {
    $this->errorRequest();
    return new Response();
}

$tgUser = $this->tgDb->getTgUser();

if ($tgUser && $this->tgRequest->getText() === '/stop') { 
    $this->tgDb->userDelete();
    return new Response(); 
}
```

**Comment by sarkisyan-m** [comment]
сделал
