### ISSUE TITLE
[code-review] Именование методов вводит в заблуждение

### ISSUE THREAD

**Issue by sheerockoff** [sarkisyan-m/TgBotInt#22]
https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Controller/TelegramController.php#L174-L197

Именование метода `antiFlood()` вводит в заблуждение. Он возвращает `true` или `false`. Нет понимания в каких случаях ожидать то или иное значение. Приходится разбираться во внутренней реализацией этого метода. Если бы метод назывался `isFlood()`, то его применение становилось бы более прозрачным и читабельным.

Метод `getMessages()` возвращает кол-во сообщений, а не сообщения, как можно было предположить из его именования.

https://github.com/jupeter/clean-code-php#function-names-should-say-what-they-do

**Comment by sarkisyan-m** [comment]
готово
