### ISSUE TITLE
[code-review] Методы, как синтаксический сахар для констант + именование

### ISSUE THREAD

**Issue by sheerockoff** [sarkisyan-m/TgBotInt#23]
https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Service/TelegramRequest.php#L7-L8

https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Service/TelegramRequest.php#L40-L48

Методы `getRequestTypeMessage()` и `getRequestTypeCallbackQuery()` существуют только для того, чтобы возвращать значения соответствующих констант. Это избыточно. Можно использовать сами константы `TelegramRequest::REQUEST_MESSAGE` и `TelegramRequest::REQUEST_CALLBACK_QUERY`.

Об именовании методов я уже писал в одной из рекомендаций. В этом классе также объявлен метод `getRequestType()`:
https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Service/TelegramRequest.php#L29-L38

Он имеет схожее название с двумя предыдущими методами и типичным примером их применения является следующий код:
https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Controller/TelegramController.php#L126

Такое схожее наименование сильно отличающихся по назначению методов вводит в заблуждение. А результаты этих методов для чего-то сравниваются. Чтобы понять эту строчку кода необходимо погружаться во внутреннюю реализацию этих методов, чтобы определиться с входными условиями блока `if`. Следующий пример реализации выглядел бы нагляднее:
```php
if ($this->tgRequest->getRequestType() === TelegramRequest::REQUEST_MESSAGE) {
    // ...
}
```

Symfony Code Convention также рекомендует "нормализовать" названия методов если речь идёт об единой предметной области класса.
> When an object has a "main" many relation with related "things" (objects, parameters, ...), the method names are normalized

https://symfony.com/doc/current/contributing/code/conventions.html#method-names

Если следовать этому соглашению, то можно переименовать метод `getRequestType()` в метод `getType()`, а константу `REQUEST_MESSAGE` в `TYPE_MESSAGE`. И придти к следующему примеру реализации:
```php
if ($this->tgRequest->getType() === TelegramRequest::TYPE_MESSAGE) {
    // ...
}
```

**Comment by sarkisyan-m** [comment]
сделал
