### ISSUE TITLE
[code-review] Метод целиком состоит из большого блока if

### ISSUE THREAD

**Issue by sheerockoff** [sarkisyan-m/TgBotInt#24]
https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Controller/TelegramController.php#L388-L490

Метод целиком состоит из большого блока `if`. Подобное можно избежать, повысив читаемость кода.

https://github.com/jupeter/clean-code-php#avoid-nesting-too-deeply-and-return-early-part-1
https://github.com/jupeter/clean-code-php#avoid-nesting-too-deeply-and-return-early-part-2

Например:
```php
if (!$this->tgRequest->getText()) {
    return false;
}

if ($this->isBotCommand('/help') || $this->isBotCommand('/start')) { 
    $this->commandHelp();
    return true; 
}

// ...
```

**Comment by sarkisyan-m** [comment]
поправил
