### ISSUE TITLE
[code-review] Незаконченная реализация метода без комментария TODO

### ISSUE THREAD

**Issue by sheerockoff** [sarkisyan-m/TgBotInt#25]
https://github.com/sarkisyan-m/TgBotInt/blob/f13ae857ada7c660af9e8c073c89028e2f8eeb80/src/Controller/TelegramController.php#L256-L262

Комментарии из этого блока кода сообщают, что реализация метода не закончена. 

Если это мёртвый код, который не используется, то его следует удалить (https://github.com/jupeter/clean-code-php#remove-dead-code).

Если это используемый метод, то подобные комментарии можно оформить как `TODO` (`ToDo`, `todo`, etc.). Например:
```php
// TODO: Реализовать метод удаления сессии пользователя.
```

Подобный комментарий легко организовывается в список дел в phpStorm, проверка `Check TODO` перед коммитом может предотвратить коммит с незаконченным функционалом, и т.п.

https://www.jetbrains.com/help/phpstorm/using-todo.html

Возможно использовать также комментарий `@todo` в `PHPDoc` блоке. Подобный комментарий может быть полезен при генерации документации. Например:

```php
/**
 * Очистить сессию пользователя.
 * @todo Реализовать метод
 */
public function deleteSession() 
{
    // ...
}
```

http://docs.phpdoc.org/references/phpdoc/tags/todo.html

**Comment by sarkisyan-m** [comment]
реализация законченная. сюда надо вставлять функции, которые сбрасывают пользовательские вводы (завершение сеанса или действия, не связанные с текущей командой вызывают триггер этого метода).
